### ISSUE TITLE
nice "continuation"

### ISSUE THREAD

**Issue by toonjoey** [averagedeveloper2k/AverageOTP#1]
Did you ever hear the tragedy of Flippy Doggenbottom the Toon? I thought not. It’s not a story the Toons would tell you. It’s a Cog legend. Flippy Doggenbottom was a member of the Toon Council, so powerful and so wise he could use the gags to influence the Toon-Up to create life… He had such a knowledge of the Cogs that he could even keep the ones he cared about from going sad. The Cog side of the war is a pathway to many abilities some consider to be unnatural. He became so powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew, then his apprentice greened him in his sleep. Ironic. He could save others from sadness, but not himself.

**Comment by averagedeveloper2k** [comment]
Aww fuck off.
